module.exports = {
  RECEIVE_USER: "RECEIVE_USER",
  LOGOUT_USER: "LOGOUT_USER",
  RECEIVE_ERRORS: "RECEIVE_ERRORS",
  RECEIVE_ALL_USERS: "RECEIVE_ALL_USERS",
  RECEIVE_ONE_USER: "RECEIVE_ONE_USER"
};
