module.exports = {
  RECEIVE_USER: "usrRECEIVE_USER",
  LOGOUT_USER: "usrLOGOUT_USER",
  RECEIVE_ERRORS: "usrRECEIVE_ERRORS",
  RECEIVE_ALL_USERS: "usrRECEIVE_ALL_USERS",
  RECEIVE_ONE_USER: "usrRECEIVE_ONE_USER"
};
